routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdressController;
use App\Http\Controllers\BannerPromoController;
use App\Http\Controllers\chartController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\FAQController;
// use App\Http\Controllers\FrontendProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MasterCategoryController;
use App\Http\Controllers\MasterProductController;
use App\Http\Controllers\MasterSizeController;
use App\Http\Controllers\MetodePembayaranController;
use App\Http\Controllers\PreviewProdukControlller;
use App\Http\Controllers\StoreSettingController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoucherKodeController;
use App\Http\Controllers\WeightOngkirController;
use App\Http\Controllers\KataSandiController;
use App\Models\MasterCategory;
use Illuminate\Support\Facades\DB;
// use Illuuse App\Http\Controllers\StoreSettingController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::prefix('/chart')->group(function () {
    Route::get('/wilshit', [chartController::class, 'wilshit'])->name('chart.wilshit');
});

// chart to checkout
Route::resource('/chart', chartController::class);

#================================ ROUTE ADMIN TRANSAKSION ===================================================
Route::middleware('auth', 'role:admin')->group(function () {
    Route::post('ubah_password',[KataSandiController::class,'reset'])->name('proses.reset.password');
    Route::resource('/admin', AdminController::class);
    Route::group(['prefix' => 'admin'], function () {
        // Route::resource('/', AdminController::class)->name('admin.index');
        Route::get('/transaksi/rejected', [TransaksiController::class, 'rejected_view'])->name('admin_transaksi.rejected');
        Route::get('/transaksi/selesai', [TransaksiController::class, 'selesai_view'])->name('admin_transaksi.selesai');
        Route::get('/transaksi/all', [TransaksiController::class, 'all_transaksi'])->name('admin_transaksi.all');
        Route::put('/transaksi/update_transaksi', [TransaksiController::class, 'update_transaksi'])->name('admin_transaksi.update_transaksi');
        Route::put('/transaksi/update_tracking', [TransaksiController::class, 'update_tracking'])->name('admin_transaksi.update_tracking');
    });
});
Route::get('admin/transaksi/detail/', [TransaksiController::class, 'detail_transaksi'])->name('admin_transaksi.detail_transaksi');
#================================ ROUTE ADMIN TRANSAKSION ===================================================

// Route::middleware('auth', 'role:admin')->group(function () {
//     Route::resource('/admin', AdminController::class);
// });


Route::get('/', [HomeController::class, 'index'])->name('homepage');


Route::prefix('customer')->group(function () {
    Route::prefix('account')->group(function () {
        Route::get('login', [LoginController::class, 'index'])->name('login')->middleware('guest');
        Route::post('login', [LoginController::class, 'login'])->name('login.post');
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');
        Route::post('registrasi', [LoginController::class, 'registrasi'])->name('registrasi');
    });
});

// ====================================================== route admin ========================================================================
// master
Route::middleware('auth', 'role:admin')->group(function () {
    Route::group(['prefix' => 'master'], function () {
        // master size
        Route::group(['prefix' => 'size'], function () {
            Route::get('/', [MasterSizeController::class, 'index'])->name('master_size');
            Route::get('/sizes', [MasterSizeController::class, 'show_data'])->name('data_size');
            Route::post('/', [MasterSizeController::class, 'store'])->name('tambah_size');
            Route::get('{id}', [MasterSizeController::class, 'edit'])->name('get_size');
            Route::put('/', [MasterSizeController::class, 'update'])->name('update_size');
            Route::delete('/', [MasterSizeController::class, 'destroy'])->name('hapus_size');
        });

        // master category
        Route::group(['prefix' => 'category'], function () {
            Route::get(
                '/',
                [MasterCategoryController::class, 'index']
            )->name('master_category');
            Route::get('/categorys', [MasterCategoryController::class, 'show_data'])->name('data_category');
            Route::post('/', [MasterCategoryController::class, 'store'])->name('tambah_category');
            Route::get('{id}', [MasterCategoryController::class, 'edit'])->name('get_category');
            Route::put(
                '/',
                [MasterCategoryController::class, 'update']
            )->name('update_category');
            Route::delete('/', [MasterCategoryController::class, 'destroy'])->name('hapus_category');
        });

        // master product
        Route::resource('/product', MasterProductController::class);
        Route::get('/products', [MasterProductController::class, 'show_data'])->name('product.dataproduct');
        Route::delete('/remove_item', [MasterProductController::class, 'remove_item'])->name('product.remove_item');
        Route::delete('/remove_kategori', [MasterProductController::class, 'remove_kategori'])->name('product.remove_kategori');
        Route::get('/products/transaksi/list/{id}', [MasterProductController::class, 'list_transaksi_selesai'])->name('product.list_transaksi_selesai');
        // Route::get('/products/penilain/{id}', [MasterProductController::class, 'penilaian_produk'])->name('product.penilaian_produk');

        // previw produk
        Route::resource('products/preview/penilain', PreviewProdukControlller::class);
        // pengaturan toko
        Route::group(['prefix' => 'pengaturan_toko'], function () {
            Route::get('/', [StoreSettingController::class, 'index'])->name('pengaturan_toko');
            Route::get('/tes', [StoreSettingController::class, 'create'])->name('a');
            Route::put('/', [StoreSettingController::class, 'update'])->name('ubah_data_toko');
            Route::put('/update_banner/{id}', [StoreSettingController::class, 'update_banner'])->name('pengaturan_toko.update_banner');
            Route::put('/update_banner_status/{id}', [StoreSettingController::class, 'update_banner_status'])->name('pengaturan_toko.update_status_banner');
            Route::put('/update_background_testimoni', [StoreSettingController::class, 'background_testimoni'])->name('pengaturan_toko.backround_testimoni');
            Route::get('/reviews', [StoreSettingController::class, 'reviews'])->name('pengaturan_toko.reviews');
            Route::get('/review/{id}', [StoreSettingController::class, 'review'])->name('pengaturan_toko.review');
            Route::post('/reviews', [StoreSettingController::class, 'make_review'])->name('pengaturan_toko.post_reviews');
            Route::put('/reviews/{id}', [StoreSettingController::class, 'edit_review'])->name('pengaturan_toko.edit_reviews');
        });

        // user master
        Route::prefix('/user')->group(function () {
            Route::get('/', [UserController::class, 'index'])->name('master.user_index');
        });
        // user contact_us
        Route::prefix('/contact_us')->group(function () {
            Route::get('/', [ContactUsController::class, 'index'])->name('contact_us.index');
        });

        //metode pembayaran
        Route::resource('/metode_pembayaran', MetodePembayaranController::class);
        Route::put('metode_pembayaran/update_status/{id}', [MetodePembayaranController::class, 'update_status'])->name('metode_pembayaran.update_status');

        //weight ongkir
        Route::resource('berat/ongkir', WeightOngkirController::class);

        //update banner promo
        Route::resource('evoucher/banner_promo', BannerPromoController::class);
        //kode voucher
        Route::resource('vocher/promo', VoucherKodeController::class);
        Route::put('vocher/promo/update_status/{id}', [VoucherKodeController::class, 'update_status'])->name('promo.update_status');

        //faq
        Route::get('faq/data', [FAQController::class, 'show_data'])->name('faq.data');
        Route::resource('faq', FAQController::class);
    });
});
// ====================================================== route frontend ========================================================================

// User Menu
Route::middleware('auth', 'role:customer')->group(function () {
    Route::prefix('user')->group(function () {
        // user profile
        Route::get('/profile', [HomeController::class, 'home_user'])->name('user.profile');
        Route::put('/profile', [HomeController::class, 'update_profile'])->name('update.profile');
        Route::put('/change/password', [LoginController::class, 'change_password'])->name('change.password');
        // penutup user profile
        Route::get('/address', [HomeController::class, 'home_address'])->name('user.address');
        Route::put('/change/default_address', [HomeController::class, 'change_default_address'])->name('change.default_address');
    });
});

Route::prefix('data')->group(function () {
    Route::get('kota/{id_address}', [HomeController::class, 'kota'])->name('get.kota');

resources/views/product.blade.php
@extends('template')

@section('judul', $title)

@section('content')

    <div class="row">
        <div class="col-md-12 mt-3">
            <div class="table-responsive">
                <table class="table table-hover" id="tblTest">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Product</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Add To Chart</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>Laptop Hp Gaming</td>
                            <form action="{{ route('chart.store') }}" method="post">
                                @csrf
                                <td>
                                    <input type="number" value="0" name="quantity" class="form-control chart-input">
                                    <input type="hidden" value="1" name="id" class="form-control id-input">
                                    <input type="hidden" name="title" value="Laptop Hp Gaming"
                                        class="form-control title-input">
                                </td>
                                <td> <button type="submit">haha</button></td>
                            </form>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Laptop Asus Predator</td>
                            <td>
                                <input type="number" value="0" class="form-control chart-input">
                                <input type="hidden" value="2" class="form-control id-input">
                                <input type="hidden" value="Laptop Asus Predator" class="form-control title-input">
                            </td>
                            <td><input type="button" class="btn btn-success" name="" id="" value="add"></td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Laptop Lenovo</td>
                            <td>
                                <input type="number" value="0" class="form-control chart-input">
                                <input type="hidden" value="3" class="form-control id-input">
                                <input type="hidden" value="Laptop Lenovo" class="form-control title-input">
                            </td>
                            <td><input type="button" class="btn btn-success" name="" id="" value="add"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @if (session()->has('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    <script>
        $(document).ready(function() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    // 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        })
        $('#tblTest input[type="button"]').click(function() {
            let quantity = $(this).closest('tr').find(".chart-input").val();
            let id = $(this).closest('tr').find(".id-input").val();
            let title = $(this).closest('tr').find(".title-input").val();
            // alert(quantity + ' id ' + id + ' Title ' + title)

            $.ajax({
                url: "{{ route('chart.store') }}",
                type: 'POST',
                data: {
                    id,
                    quantity,
                    title,
                },
                dataType: 'json',
                success: function(ok) {
                    if (ok.status == true) {
                        window.location.href =
                            "{{ route('chart.wilshit') }}";
                    }
                }
            })
        });
    </script>
@endsection

resources/views/template.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Chart Session</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

</head>

<body>
    <div class="container">
        <h1 class="mt-3">@yield('judul')</h1>
        @yield('content')
    </div>

</body>

</html>

resources/views/wilshit.blade.php
@extends('template')

@section('judul', $title)

@section('content')
    @if (session('success'))
        {{ session()->get('success') }}
    @endif
    <div class="row">
        <div class="col-md-12 mt-3">
            {{ var_dump(count($data) == 0) }}
            @if (!is_null($data))


                <div class="table-responsive">
                    <table class="table table-hover" id="tblTest">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Product</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php($i = 1)
                            @foreach ($data as $id => $co)
                                <tr>
                                    <th scope="row">{{ $i++ }}</th>
                                    <td>{{ $co['title'] }}</td>
                                    <td>{{ $co['quantity'] }}</td>
                                    <td><input type="button" class="btn btn-success" name="" id="" value="Delete"></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @else
                hehaha
            @endif
        </div>
    </div>
@endsection