routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdressController;
use App\Http\Controllers\BannerPromoController;
use App\Http\Controllers\chartController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\FAQController;
// use App\Http\Controllers\FrontendProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MasterCategoryController;
use App\Http\Controllers\MasterProductController;
use App\Http\Controllers\MasterSizeController;
use App\Http\Controllers\MetodePembayaranController;
use App\Http\Controllers\PreviewProdukControlller;
use App\Http\Controllers\StoreSettingController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoucherKodeController;
use App\Http\Controllers\WeightOngkirController;
use App\Http\Controllers\KataSandiController;
use App\Models\MasterCategory;
use Illuminate\Support\Facades\DB;
// use Illuuse App\Http\Controllers\StoreSettingController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::prefix('/chart')->group(function () {
    Route::get('/wilshit', [chartController::class, 'wilshit'])->name('chart.wilshit');
});

// chart to checkout
Route::resource('/chart', chartController::class);

#================================ ROUTE ADMIN TRANSAKSION ===================================================
Route::middleware('auth', 'role:admin')->group(function () {
    Route::post('ubah_password',[KataSandiController::class,'reset'])->name('proses.reset.password');
    Route::resource('/admin', AdminController::class);
    Route::group(['prefix' => 'admin'], function () {
        // Route::resource('/', AdminController::class)->name('admin.index');
        Route::get('/transaksi/rejected', [TransaksiController::class, 'rejected_view'])->name('admin_transaksi.rejected');
        Route::get('/transaksi/selesai', [TransaksiController::class, 'selesai_view'])->name('admin_transaksi.selesai');
        Route::get('/transaksi/all', [TransaksiController::class, 'all_transaksi'])->name('admin_transaksi.all');
        Route::put('/transaksi/update_transaksi', [TransaksiController::class, 'update_transaksi'])->name('admin_transaksi.update_transaksi');
        Route::put('/transaksi/update_tracking', [TransaksiController::class, 'update_tracking'])->name('admin_transaksi.update_tracking');
    });
});
Route::get('admin/transaksi/detail/', [TransaksiController::class, 'detail_transaksi'])->name('admin_transaksi.detail_transaksi');
#================================ ROUTE ADMIN TRANSAKSION ===================================================

// Route::middleware('auth', 'role:admin')->group(function () {
//     Route::resource('/admin', AdminController::class);
// });


Route::get('/', [HomeController::class, 'index'])->name('homepage');


Route::prefix('customer')->group(function () {
    Route::prefix('account')->group(function () {
        Route::get('login', [LoginController::class, 'index'])->name('login')->middleware('guest');
        Route::post('login', [LoginController::class, 'login'])->name('login.post');
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');
        Route::post('registrasi', [LoginController::class, 'registrasi'])->name('registrasi');
    });
});

// ====================================================== route admin ========================================================================
// master
Route::middleware('auth', 'role:admin')->group(function () {
    Route::group(['prefix' => 'master'], function () {
        // master size
        Route::group(['prefix' => 'size'], function () {
            Route::get('/', [MasterSizeController::class, 'index'])->name('master_size');
            Route::get('/sizes', [MasterSizeController::class, 'show_data'])->name('data_size');
            Route::post('/', [MasterSizeController::class, 'store'])->name('tambah_size');
            Route::get('{id}', [MasterSizeController::class, 'edit'])->name('get_size');
            Route::put('/', [MasterSizeController::class, 'update'])->name('update_size');
            Route::delete('/', [MasterSizeController::class, 'destroy'])->name('hapus_size');
        });

        // master category
        Route::group(['prefix' => 'category'], function () {
            Route::get(
                '/',
                [MasterCategoryController::class, 'index']
            )->name('master_category');
            Route::get('/categorys', [MasterCategoryController::class, 'show_data'])->name('data_category');
            Route::post('/', [MasterCategoryController::class, 'store'])->name('tambah_category');
            Route::get('{id}', [MasterCategoryController::class, 'edit'])->name('get_category');
            Route::put(
                '/',
                [MasterCategoryController::class, 'update']
            )->name('update_category');
            Route::delete('/', [MasterCategoryController::class, 'destroy'])->name('hapus_category');
        });

        // master product
        Route::resource('/product', MasterProductController::class);
        Route::get('/products', [MasterProductController::class, 'show_data'])->name('product.dataproduct');
        Route::delete('/remove_item', [MasterProductController::class, 'remove_item'])->name('product.remove_item');
        Route::delete('/remove_kategori', [MasterProductController::class, 'remove_kategori'])->name('product.remove_kategori');
        Route::get('/products/transaksi/list/{id}', [MasterProductController::class, 'list_transaksi_selesai'])->name('product.list_transaksi_selesai');
        // Route::get('/products/penilain/{id}', [MasterProductController::class, 'penilaian_produk'])->name('product.penilaian_produk');

        // previw produk
        Route::resource('products/preview/penilain', PreviewProdukControlller::class);
        // pengaturan toko
        Route::group(['prefix' => 'pengaturan_toko'], function () {
            Route::get('/', [StoreSettingController::class, 'index'])->name('pengaturan_toko');
            Route::get('/tes', [StoreSettingController::class, 'create'])->name('a');
            Route::put('/', [StoreSettingController::class, 'update'])->name('ubah_data_toko');
            Route::put('/update_banner/{id}', [StoreSettingController::class, 'update_banner'])->name('pengaturan_toko.update_banner');
            Route::put('/update_banner_status/{id}', [StoreSettingController::class, 'update_banner_status'])->name('pengaturan_toko.update_status_banner');
            Route::put('/update_background_testimoni', [StoreSettingController::class, 'background_testimoni'])->name('pengaturan_toko.backround_testimoni');
            Route::get('/reviews', [StoreSettingController::class, 'reviews'])->name('pengaturan_toko.reviews');
            Route::get('/review/{id}', [StoreSettingController::class, 'review'])->name('pengaturan_toko.review');
            Route::post('/reviews', [StoreSettingController::class, 'make_review'])->name('pengaturan_toko.post_reviews');
            Route::put('/reviews/{id}', [StoreSettingController::class, 'edit_review'])->name('pengaturan_toko.edit_reviews');
        });

        // user master
        Route::prefix('/user')->group(function () {
            Route::get('/', [UserController::class, 'index'])->name('master.user_index');
        });
        // user contact_us
        Route::prefix('/contact_us')->group(function () {
            Route::get('/', [ContactUsController::class, 'index'])->name('contact_us.index');
        });

        //metode pembayaran
        Route::resource('/metode_pembayaran', MetodePembayaranController::class);
        Route::put('metode_pembayaran/update_status/{id}', [MetodePembayaranController::class, 'update_status'])->name('metode_pembayaran.update_status');

        //weight ongkir
        Route::resource('berat/ongkir', WeightOngkirController::class);

        //update banner promo
        Route::resource('evoucher/banner_promo', BannerPromoController::class);
        //kode voucher
        Route::resource('vocher/promo', VoucherKodeController::class);
        Route::put('vocher/promo/update_status/{id}', [VoucherKodeController::class, 'update_status'])->name('promo.update_status');

        //faq
        Route::get('faq/data', [FAQController::class, 'show_data'])->name('faq.data');
        Route::resource('faq', FAQController::class);
    });
});
// ====================================================== route frontend ========================================================================

// User Menu
Route::middleware('auth', 'role:customer')->group(function () {
    Route::prefix('user')->group(function () {
        // user profile
        Route::get('/profile', [HomeController::class, 'home_user'])->name('user.profile');
        Route::put('/profile', [HomeController::class, 'update_profile'])->name('update.profile');
        Route::put('/change/password', [LoginController::class, 'change_password'])->name('change.password');
        // penutup user profile
        Route::get('/address', [HomeController::class, 'home_address'])->name('user.address');
        Route::put('/change/default_address', [HomeController::class, 'change_default_address'])->name('change.default_address');
    });
});

Route::prefix('data')->group(function () {
    Route::get('kota/{id_address}', [HomeController::class, 'kota'])->name('get.kota');

resources/views/template_admin/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link href="{{ asset('file/img/logo/logo2.png') }}" rel="icon" />
    <link href="{{ asset('assets_frontend/images/logo/logo-distro.jpeg') }}" rel="icon">
    <title>{{ config('app.name') }} | @yield('title') </title>
    <link href="{{ asset('file/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('file/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('file/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('file/css/ruang-admin.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('file/select-type/css/bootstrap-select.min.css') }}" rel="stylesheet" type="text/css" />

    <script src="{{ asset('file/vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('file/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('file/vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <!-- Page level plugins -->
    <script src="{{ asset('file/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('file/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('file/select-type/js/bootstrap-select.min.js') }}"></script>

    <link rel="stylesheet" type="text/css" href="{{ asset('assets_frontend/toast/toastr.min.css') }}">
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"
        integrity="sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script> --}}

    {{-- <script src="{{ asset('file/vendor/sweatalert/sweetalert.min.js') }}"></script>
    @include('sweetalert::alert') --}}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.0.1/tinymce.min.js"></script> --}}
    {{-- <script src="https://cdn.ckeditor.com/ckeditor5/33.0.0/classic/ckeditor.js"></script> --}}

</head>

<body id="page-top">
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav sidebar sidebar-light accordion sidebar-brand" id="accordionSidebar">
            @include('template_admin.navbar')
        </ul>
        <!-- Sidebar -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <!-- TopBar -->

                @include('template_admin.topbar')
                <!-- Topbar -->

                <!-- Container Fluid-->

                <div class="container-fluid" id="container-wrapper">
                    @yield('container')
                </div>

                <!---Container Fluid-->
            </div>
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>copyright &copy;
                            <script>
                                document.write(new Date().getFullYear());
                            </script>

                        </span>
                    </div>
                </div>
            </footer>
            <!-- Footer -->
        </div>
    </div>

    <!-- Scroll to top -->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    {{-- modal reset password  --}}

    <div class="modal" id="modalPassword" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Ganti Password </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="exampleInputPassword1">Password Lama</label>
                    <input type="password" class="form-control" id="ubahPasswordLama" placeholder="Password Lama Anda">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password Baru</label>
                    <input type="password" class="form-control" id="ubahPasswordBaru" placeholder="Password Baru">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Konfirmasi Password Baru</label>
                    <input type="password" class="form-control" id="ubahKonfirmasiPasswordBaru" placeholder="Konfirmasi Password Baru">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="prosesUbahPassword()">Simpan</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            </div>
        </div>
        </div>

</body>

<script src="{{ asset('file/js/ruang-admin.min.js') }}"></script>
<script src="{{ asset('file/vendor/chart.js/Chart.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets_frontend/toast/toastr.min.js') }}"></script>

<script>
    $(document).ready(function() {
        toastr.options = {
            'closeButton': true,
            'debug': false,
            'newestOnTop': false,
            'progressBar': false,
            'positionClass': 'toast-top-right',
            'preventDuplicates': false,
            'showDuration': '1000',
            'hideDuration': '1000',
            'timeOut': '5000',
            'extendedTimeOut': '1000',
            'showEasing': 'swing',
            'hideEasing': 'linear',
            'showMethod': 'fadeIn',
            'hideMethod': 'fadeOut',
        }

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        });
    });

    const prosesUbahPassword=()=>{
        var passBaru=$('#ubahPasswordBaru').val();
        var passKonfirmasi=$('#ubahKonfirmasiPasswordBaru').val();
        var passLama=$('#ubahPasswordLama').val()
        if(passBaru=="" || passLama=="" || passKonfirmasi==""){
            Swal.fire(
                'Gagal!',
                'Harap isi semua form!',
                'error'
            )
        }else if($('#ubahPasswordBaru').val() != $('#ubahKonfirmasiPasswordBaru').val()) {
             Swal.fire(
                'Gagal!',
                'Password baru dan konfirmasi password baru harus sama!',
                'error'
            )
        }else{
            $.ajax({
                type: "POST",
                url: "{{ route('proses.reset.password') }}",
                data: {
                    "passLama":passLama,
                    "passBaru":passBaru,
                    "passKonfirmasi":passKonfirmasi
                },
                success: function (response) {
                    Swal.fire(
                        'Berhasil!',
                        'Password berhasil diperbaharui!',
                        'success'
                    )
                },error: function (xhr, ajaxOptions, thrownError) {
                     Swal.fire(
                        'Gagal!',
                        xhr.responseJSON.message,
                        'error'
                    )
                }
            });
    }
    }
</script>
@yield('js')
</html>

resources/views/template_admin/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link href="{{ asset('img/logo/logo.png');}}" rel="icon">
  <title>SSO - Login</title>
  <link href="{{ asset('file/vendor/fontawesome-free/css/all.min.css');}}" rel="stylesheet" type="text/css">
  <link href="{{ asset('file/vendor/bootstrap/css/bootstrap.min.css');}}" rel="stylesheet" type="text/css">
  <link href="{{ asset('file/css/ruang-admin.min.css');}}" rel="stylesheet">

</head>

<body class="bg-gradient-login">
  <!-- Login Content -->
  <div class="container-login">
    <div class="row justify-content-center">
      <div class="col-xl-6 col-lg-12 col-md-9">
        <div class="card shadow-sm my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-12">
                <div class="login-form">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Login</h1>
                  </div>
                  @if (session()->has('login_error'))
                    <div class="alert alert-danger"> {{ session('login_error')}}</div>
                  @endif
                  <form class="user" action="{{ route('login')}}" method="POST">
                    @csrf
                      @if (session()->has('info'))
                        <div class="alert alert-success"> {{ session('info')}}</div>
                      @endif
                    <div class="form-group">
                      <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}"
                        placeholder="Enter Email Address">
                       @error('email')
                            <div class="invalid-feedback">{{$message}}</div>
                       @enderror
                    </div>
                    <div class="form-group">
                      <input type="password" name="password" class="form-control"  placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small" style="line-height: 1.5rem;">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember
                          Me</label>
                      </div>
                    </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary btn-block">Login</a>
                    </div>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="font-weight-bold small" href="{{url('/')}}">Back to home</a>
                  </div>
                  <div class="text-center">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Login Content -->
  <script src="{{ asset('vendor/jquery/jquery.min.js');}}"></script>
  <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js');}}"></script>
  <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js');}}"></script>
  <script src="{{ asset('js/ruang-admin.min.js');}}"></script>
</body>

</html>

resources/views/template_admin/navbar.blade.php
<a style="background-color: #d2b19b !important;" class="sidebar-brand d-flex align-items-center justify-content-center"
    href="{{ url('/') }}">
    <div class="sidebar-brand-icon">
        <img src="{{ asset('file/img/logo/logo-distro.jpeg') }}" />
    </div>
    <div class="sidebar-brand-text mx-3">BillDistro</div>
</a>

<hr class="sidebar-divider my-0" />
<li class="nav-item  ">
    <a class="nav-link" href="{{route('admin.index')}}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
</li>
<hr class="sidebar-divider" />
<div class="sidebar-heading">Features</div>
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBootstrap" aria-expanded="true"
        aria-controls="collapseBootstrap">
        <i class="far fa-fw fa-window-maximize"></i>
        <span>Data Master</span>
    </a>
    <div id="collapseBootstrap" class="collapse" aria-labelledby="headingBootstrap"
        data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Data Master</h6>
            {{-- <a class="collapse-item" href="">Role</a> --}}
            <a class="collapse-item" href="{{ route('master.user_index') }}">User</a>
            <a class="collapse-item" href="{{ route('master_size') }}">Size</a>
            <a class="collapse-item" href="{{ route('master_category') }}">Kategori</a>
        </div>
    </div>
</li>
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBootstrap1" aria-expanded="true"
        aria-controls="collapseBootstrap1">
        <i class="far fa-fw fa-window-maximize"></i>
        <span>Data Produk</span>
    </a>
    <div id="collapseBootstrap1" class="collapse" aria-labelledby="headingBootstrap"
        data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Produk</h6>
            <a class="collapse-item" href="{{ route('product.index') }}">Daftar Produk</a>
            <a class="collapse-item" href="{{ route('product.create') }}">Tambah Produk</a>
        </div>
    </div>
</li>
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBootstrap2" aria-expanded="true"
        aria-controls="collapseBootstrap">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <span>Data Transaksi</span>
    </a>
    <div id="collapseBootstrap2" class="collapse" aria-labelledby="headingBootstrap"
        data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Data Transaksi</h6>
            {{-- <a class="collapse-item" href="">Role</a> --}}
            <a class="collapse-item" href="{{ route('metode_pembayaran.index') }}">Metode Pembayaran</a>
            <a class="collapse-item" href="{{ route('ongkir.index') }}">Berat Ongkir</a>
            <a class="collapse-item" href="{{ route('banner_promo.index') }}">E-voucher / Promo</a>
            <a class="collapse-item" href="{{ route('admin_transaksi.all') }}">Transaksi</a>
            <a class="collapse-item" href="{{ route('admin_transaksi.selesai') }}">Transaksi Selesai</a>
            <a class="collapse-item" href="{{ route('admin_transaksi.rejected') }}">Transaksi Rejected</a>
            <a class="collapse-item" href="{{ route('penilain.index') }}">All Review Produk</a>
        </div>
    </div>
</li>
<li class="nav-item">
    <a class="nav-link collapsed" href="{{ route('contact_us.index') }}">
        <i class="fas fa-envelope fa-fw  mr-2"></i>
        <span>Contact Us / Pesan</span>
    </a>
</li>
<li class="nav-item">
    <a class="nav-link collapsed" href="{{ route('pengaturan_toko') }}">
        <i class="fas fa-cogs fa-sm fa-fw mr-2"></i>
        <span>Pengaturan Toko</span>
    </a>
</li>
<li class="nav-item">
    <a class="nav-link collapsed" href="{{ route('faq.index') }}">
        <i class="fas fa-question fa-sm fa-fw mr-2"></i>
        <span>FAQ</span>
    </a>
</li>