routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdressController;
use App\Http\Controllers\BannerPromoController;
use App\Http\Controllers\chartController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\FAQController;
// use App\Http\Controllers\FrontendProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MasterCategoryController;
use App\Http\Controllers\MasterProductController;
use App\Http\Controllers\MasterSizeController;
use App\Http\Controllers\MetodePembayaranController;
use App\Http\Controllers\PreviewProdukControlller;
use App\Http\Controllers\StoreSettingController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoucherKodeController;
use App\Http\Controllers\WeightOngkirController;
use App\Http\Controllers\KataSandiController;
use App\Models\MasterCategory;
use Illuminate\Support\Facades\DB;
// use Illuuse App\Http\Controllers\StoreSettingController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::prefix('/chart')->group(function () {
    Route::get('/wilshit', [chartController::class, 'wilshit'])->name('chart.wilshit');
});

// chart to checkout
Route::resource('/chart', chartController::class);

#================================ ROUTE ADMIN TRANSAKSION ===================================================
Route::middleware('auth', 'role:admin')->group(function () {
    Route::post('ubah_password',[KataSandiController::class,'reset'])->name('proses.reset.password');
    Route::resource('/admin', AdminController::class);
    Route::group(['prefix' => 'admin'], function () {
        // Route::resource('/', AdminController::class)->name('admin.index');
        Route::get('/transaksi/rejected', [TransaksiController::class, 'rejected_view'])->name('admin_transaksi.rejected');
        Route::get('/transaksi/selesai', [TransaksiController::class, 'selesai_view'])->name('admin_transaksi.selesai');
        Route::get('/transaksi/all', [TransaksiController::class, 'all_transaksi'])->name('admin_transaksi.all');
        Route::put('/transaksi/update_transaksi', [TransaksiController::class, 'update_transaksi'])->name('admin_transaksi.update_transaksi');
        Route::put('/transaksi/update_tracking', [TransaksiController::class, 'update_tracking'])->name('admin_transaksi.update_tracking');
    });
});
Route::get('admin/transaksi/detail/', [TransaksiController::class, 'detail_transaksi'])->name('admin_transaksi.detail_transaksi');
#================================ ROUTE ADMIN TRANSAKSION ===================================================

// Route::middleware('auth', 'role:admin')->group(function () {
//     Route::resource('/admin', AdminController::class);
// });


Route::get('/', [HomeController::class, 'index'])->name('homepage');


Route::prefix('customer')->group(function () {
    Route::prefix('account')->group(function () {
        Route::get('login', [LoginController::class, 'index'])->name('login')->middleware('guest');
        Route::post('login', [LoginController::class, 'login'])->name('login.post');
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');
        Route::post('registrasi', [LoginController::class, 'registrasi'])->name('registrasi');
    });
});

// ====================================================== route admin ========================================================================
// master
Route::middleware('auth', 'role:admin')->group(function () {
    Route::group(['prefix' => 'master'], function () {
        // master size
        Route::group(['prefix' => 'size'], function () {
            Route::get('/', [MasterSizeController::class, 'index'])->name('master_size');
            Route::get('/sizes', [MasterSizeController::class, 'show_data'])->name('data_size');
            Route::post('/', [MasterSizeController::class, 'store'])->name('tambah_size');
            Route::get('{id}', [MasterSizeController::class, 'edit'])->name('get_size');
            Route::put('/', [MasterSizeController::class, 'update'])->name('update_size');
            Route::delete('/', [MasterSizeController::class, 'destroy'])->name('hapus_size');
        });

        // master category
        Route::group(['prefix' => 'category'], function () {
            Route::get(
                '/',
                [MasterCategoryController::class, 'index']
            )->name('master_category');
            Route::get('/categorys', [MasterCategoryController::class, 'show_data'])->name('data_category');
            Route::post('/', [MasterCategoryController::class, 'store'])->name('tambah_category');
            Route::get('{id}', [MasterCategoryController::class, 'edit'])->name('get_category');
            Route::put(
                '/',
                [MasterCategoryController::class, 'update']
            )->name('update_category');
            Route::delete('/', [MasterCategoryController::class, 'destroy'])->name('hapus_category');
        });

        // master product
        Route::resource('/product', MasterProductController::class);
        Route::get('/products', [MasterProductController::class, 'show_data'])->name('product.dataproduct');
        Route::delete('/remove_item', [MasterProductController::class, 'remove_item'])->name('product.remove_item');
        Route::delete('/remove_kategori', [MasterProductController::class, 'remove_kategori'])->name('product.remove_kategori');
        Route::get('/products/transaksi/list/{id}', [MasterProductController::class, 'list_transaksi_selesai'])->name('product.list_transaksi_selesai');
        // Route::get('/products/penilain/{id}', [MasterProductController::class, 'penilaian_produk'])->name('product.penilaian_produk');

        // previw produk
        Route::resource('products/preview/penilain', PreviewProdukControlller::class);
        // pengaturan toko
        Route::group(['prefix' => 'pengaturan_toko'], function () {
            Route::get('/', [StoreSettingController::class, 'index'])->name('pengaturan_toko');
            Route::get('/tes', [StoreSettingController::class, 'create'])->name('a');
            Route::put('/', [StoreSettingController::class, 'update'])->name('ubah_data_toko');
            Route::put('/update_banner/{id}', [StoreSettingController::class, 'update_banner'])->name('pengaturan_toko.update_banner');
            Route::put('/update_banner_status/{id}', [StoreSettingController::class, 'update_banner_status'])->name('pengaturan_toko.update_status_banner');
            Route::put('/update_background_testimoni', [StoreSettingController::class, 'background_testimoni'])->name('pengaturan_toko.backround_testimoni');
            Route::get('/reviews', [StoreSettingController::class, 'reviews'])->name('pengaturan_toko.reviews');
            Route::get('/review/{id}', [StoreSettingController::class, 'review'])->name('pengaturan_toko.review');
            Route::post('/reviews', [StoreSettingController::class, 'make_review'])->name('pengaturan_toko.post_reviews');
            Route::put('/reviews/{id}', [StoreSettingController::class, 'edit_review'])->name('pengaturan_toko.edit_reviews');
        });

        // user master
        Route::prefix('/user')->group(function () {
            Route::get('/', [UserController::class, 'index'])->name('master.user_index');
        });
        // user contact_us
        Route::prefix('/contact_us')->group(function () {
            Route::get('/', [ContactUsController::class, 'index'])->name('contact_us.index');
        });

        //metode pembayaran
        Route::resource('/metode_pembayaran', MetodePembayaranController::class);
        Route::put('metode_pembayaran/update_status/{id}', [MetodePembayaranController::class, 'update_status'])->name('metode_pembayaran.update_status');

        //weight ongkir
        Route::resource('berat/ongkir', WeightOngkirController::class);

        //update banner promo
        Route::resource('evoucher/banner_promo', BannerPromoController::class);
        //kode voucher
        Route::resource('vocher/promo', VoucherKodeController::class);
        Route::put('vocher/promo/update_status/{id}', [VoucherKodeController::class, 'update_status'])->name('promo.update_status');

        //faq
        Route::get('faq/data', [FAQController::class, 'show_data'])->name('faq.data');
        Route::resource('faq', FAQController::class);
    });
});
// ====================================================== route frontend ========================================================================

// User Menu
Route::middleware('auth', 'role:customer')->group(function () {
    Route::prefix('user')->group(function () {
        // user profile
        Route::get('/profile', [HomeController::class, 'home_user'])->name('user.profile');
        Route::put('/profile', [HomeController::class, 'update_profile'])->name('update.profile');
        Route::put('/change/password', [LoginController::class, 'change_password'])->name('change.password');
        // penutup user profile
        Route::get('/address', [HomeController::class, 'home_address'])->name('user.address');
        Route::put('/change/default_address', [HomeController::class, 'change_default_address'])->name('change.default_address');
    });
});

Route::prefix('data')->group(function () {
    Route::get('kota/{id_address}', [HomeController::class, 'kota'])->name('get.kota');

resources/views/layout_admin/master_faq.blade.php
@extends('template_admin.admin')

@section('title', 'Master FAQ')
@section('container')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Master FAQ</h1>

    </div>

    <!-- Row -->
    <div class="row">
        <!-- Datatables -->
        <div class="col-lg-12">
            <div class="from-group mb-2">
                <button class="btn btn-primary" onclick="tambah()" value="new">Tambah FAQ</button>
            </div>
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables</h6> -->
                </div>
                <div class="table-responsive p-3">
                    <table class="table align-items-center table-flush" id="dataTable">
                        <thead class="thead-light">
                            <tr>
                                <th>No</th>
                                <th>Pertanyaan</th>
                                <th>Jawaban</th>
                                <th>Sering Ditanyakan</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>





    </div>
    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Tambah FAQ</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="" name="form" id="form" enctype="multipart/form-data">
                        <div class="form-group">
                            @csrf
                            <label for="size_name">Pertanyaaan</label>
                            <input type="hidden" class="form-control" id="id" name="id">
                            <input type="text" class="form-control" id="question" name="question">
                            <div id="method"></div>
                        </div>
                        <div class="form-group">
                            <label for="size_name">Jawaban</label>
                            <input type="text" class="form-control" id="answer" name="answer">
                        </div>
                        <div class="form-group">
                            <label for="">Sering Ditanyakan</label>
                            <select class="form-control" id="most_question" name="most_question">
                                <option value=>Pilih Jawaban </option>
                                <option value=1>Ya</option>
                                <option value=0>Tidak</option>
                            </select>
                        </div>
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                    <button type="button" class="btn btn-primary btn-save" id="tombolsimpan">Simpan</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        // datatabel
        var table = $('#dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('faq.data') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'question',
                    name: 'question'
                },
                {
                    data: 'answer',
                    name: 'answer'
                },
                {
                    data: 'most_question',
                    name: 'most_question'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: true,
                    searchable: true
                },
            ]
        });


        function open_modal(judul, tombolSimpan, method) {
            $('#modal').modal('show');
            $('#tombolsimpan').text(tombolSimpan);
            $('.modal-title').text(judul);
            $('#form')[0].reset();
            if (method != 'edit') {
                $("input[name=id]").val('');
                $("input[name=_method]").val('');
                $('#tombolsimpan').attr('onclick', 'aksi("tambah")')
            } else {
                $('#tombolsimpan').attr('onclick', 'aksi("edit")')
            }
        };

        function tambah() {
            open_modal('Tambah FAQ', 'Simpan', 'tambah')
        }

        function edit(id) {
            var link = " {{ route('faq.edit', 'id') }}";
            var link_tujuan = link.replace("id", id);
            $.ajax({
                type: "get",
                url: link_tujuan,
                success: function(response) {
                    open_modal('Edit FAQ', 'Ubah', 'edit')
                    $('#id').val(response.id);
                    $('#question').val(response.question);
                    $('#answer').val(response.answer);
                    $('#most_question').val(response.most_question);
                    $('#method').html('@method("put")')
                }
            });
        }

        function hapus(id) {
            var link = " {{ route('faq.destroy', 'id') }}";
            link = link.replace("id", id);
            Swal.fire({
                title: 'Apakah anda yakin?',
                text: "Data yang dihapus tidak dapat dikembalikan lagi!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal',
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "post",
                        url: link,
                        data: {
                            "id": id,
                            "_method": "delete",
                            "_token": "{{ @csrf_token() }}"
                        },
                        success: function(response) {
                            if (response.success == true) {
                                $('#modal').modal('hide');
                                Swal.fire(
                                    'Berhasil!',
                                    'Data berhasil dihapus!',
                                    'success'
                                )
                                table.ajax.reload();
                            } else {
                                Swal.fire(
                                    'Gagal!',
                                    'Data gagal dihapus!',
                                    'error'
                                )
                            }
                        }
                    });
                }
            })
        }

        function aksi(method) {
            if (method == 'tambah') {
                $.ajax({
                    type: "post",
                    url: "{{ route('faq.store') }}",
                    data: $('#form').serialize(),
                    success: function(response) {

                        if (response.success == true) {
                            $('#modal').modal('hide');
                            Swal.fire(
                                'Berhasil!',
                                'Data berhasil disimpan!',
                                'success'
                            )
                            table.ajax.reload();
                        } else {
                            Swal.fire(
                                'Gagal!',
                                'Data gagal disimpan!',
                                'error'
                            )
                        }
                    }
                });

            } else if (method == 'edit') {
                var link = " {{ route('faq.update', 'id') }}";
                link = link.replace("id", $('#id').val());
                $.ajax({
                    type: "post",
                    url: link,
                    data: $('#form').serialize(),
                    success: function(response) {
                        if (response.success == true) {
                            $('#modal').modal('hide');
                            Swal.fire(
                                'Berhasil!',
                                'Data berhasil disimpan!',
                                'success'
                            )
                            table.ajax.reload();
                        } else {
                            Swal.fire(
                                'Gagal!',
                                'Data gagal disimpan!',
                                'error'
                            )
                        }
                    }
                });

            }

        }
    </script>
@endsection

resources/views/layout_admin/master_metode_pembayaran.blade.php
@extends('template_admin.admin')

@section('title', 'Metode Pembayaran')
@section('container')
<div class="row mt-3">
    <!-- Datatables -->
    <div class="col-lg-12">
        <div class="from-group mb-2">
            <a class="btn btn-primary btn-pembayaran" value="new" href="javascript:void(0)"><i
                    class="fa fa-plus-circle"></i> Tambah</a>
        </div>
        {{-- <div class="from-group mb-2">
            <button class="btn btn-primary" onclick="tambah()" value="new">Tambah Data</button>
        </div> --}}
        <div class="card mb-4">
            <div class="card-header">Metode Pembayaran</div>
            {{-- <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables</h6> -->
            </div> --}}
            <div class="table-responsive p-3">
                <table class="table align-items-center table-flush" id="dataTableNoRek" style="width: 100">
                    <thead class="thead-light">
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Kode</th>
                            <th>No.Rek</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Modal Pembayaran -->
<div id="modal_pembayaran" class="modal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalCenterTitle" aria-hidden="true" style="overflow: auto !important;">
    <div class="modal-dialog modal-dialog-centered " role="document">
        <div class="modal-content change-address">
            <div class="modal-header">
                <h5 class="modal-title-pembayaran" id="exampleModalLabel">Tambah Metode Pembayaran</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form action="" id="form-pembayaran">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="">Nama</label>
                        <input type="hidden" class="form-control" id="id_pembayaran" name="id_pembayaran">
                        <select name="nama_pembayaran" id="nama_pembayaran" class="form-control" id="">
                            <option value="0"> Pilih</option>
                            <option value="assets_frontend/images/payment/bca.svg"> BCA</option>
                            <option value="assets_frontend/images/payment/bjb.svg"> BJB</option>
                            <option value="assets_frontend/images/payment/BNI.svg"> BNI</option>
                            <option value="assets_frontend/images/payment/cimb.webp"> CIMB</option>
                            <option value="assets_frontend/images/payment/dana.svg"> DANA</option>
                            <option value="assets_frontend/images/payment/fastpay.png"> Fastpay</option>
                            <option value="assets_frontend/images/payment/gopay.svg"> GOPAY</option>
                            <option value="assets_frontend/images/payment/mandiri.svg"> MANDIRI</option>
                            <option value="assets_frontend/images/payment/ovo.svg"> OVO</option>
                            <option value="assets_frontend/images/payment/shopeepay.svg"> Shopeepay</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="">Kode</label>
                        <input type="text" class="form-control" id="kode_pembayaran" name="kode_pembayaran">
                    </div>
                    <div class="form-group">
                        <label for="">No.Rek</label>
                        <input type="text" class="form-control" id="norek_pembayaran"
                            name="norek_pembayaran">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary add-pembayaran" value="0">Simpan</button>
                    <button type="button" class="btn btn-secondary close-address"
                        data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('js')
<script>
       // Bagian pembayaran
       let dataTableNoRek
        $(document).ready(function() {
            // norek
            dataTableNoRek = $('#dataTableNoRek').DataTable({
                prossecing: true,
                serverSide: true,
                ajax: "{{ route('metode_pembayaran.index') }}",
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex'
                    },
                    {
                        data: 'nama',
                        name: 'nama'
                    },
                    {
                        data: 'kode',
                        name: 'kode'
                    },
                    {
                        data: 'no_rek',
                        name: 'no_rek'
                    },
                    {
                        data: 'action',
                        name: 'action'
                    }
                ]
            });


            $(document).on('click', '.btn-pembayaran', function() {
                $('#modal_pembayaran').modal('show');
                $('#form-pembayaran')[0].reset();
                $('.modal-title-pembayaran').html('Tambah Metode Pembayaran');
                $('.add-pembayaran').val(0);
            });
            $(document).on('click', '.edit-pembayaran', function() {
                $('#modal_pembayaran').modal('show');
                let id = $(this).data('id');
                $('.modal-title-pembayaran').html('Edit Metode Pembayaran');
                $('.add-pembayaran').val(1);
                let url = "{{ route('metode_pembayaran.edit', ['metode_pembayaran' => ':id']) }}";
                url = url.replace(":id", id);
                $.ajax({
                    method: 'GET',
                    url: url,
                    success: function(data) {
                        if (data.status == true) {
                            toastr.success(data.msg);
                            $('#modal_pembayaran').modal('show');
                            $('#id_pembayaran').val(data.data.id);
                            $('#nama_pembayaran').val(data.data.nama);
                            $('#kode_pembayaran').val(data.data.kode);
                            $('#norek_pembayaran').val(data.data.no_rek);
                        } else {
                            toastr.warning(data.msg);
                        }
                    }
                });
            });
            $(document).on('click', '.hapus-pembayaran', function() {
                let id = $(this).data('id');
                Swal.fire({
                    title: 'Apakah anda yakin?',
                    text: "Data yang dihapus tidak dapat dikembalikan lagi!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Hapus',
                    cancelButtonText: 'Batal',
                }).then((result) => {
                    if (result.isConfirmed) {
                        $(this).parent().closest('.address').remove();
                        let url =
                            "{{ route('metode_pembayaran.destroy', ['metode_pembayaran' => ':id']) }}";
                        url = url.replace(":id", id);
                        $.ajax({
                            method: 'DELETE',
                            url: url,
                            success: function(data) {
                                if (data.status == true) {
                                    toastr.success(data.msg);
                                    dataTableNoRek.ajax.reload();
                                } else {
                                    toastr.error('Gagal, Hapus data.');
                                }
                            }
                        });
                    }
                });
            });
        });


        $(document).on('click', '.add-pembayaran', function(e) {
            e.preventDefault();
            let data = $('#form-pembayaran').serializeArray();
            let check = $('.add-pembayaran').val();
            let url;
            let method;
            if (check == 0) {
                url = "{{ route('metode_pembayaran.store') }}";
            } else if (check == 1) {
                let id = $('#id_pembayaran').val();
                url = "{{ route('metode_pembayaran.update', ['metode_pembayaran' => ':id']) }}";
                url = url.replace(":id", id);
                data = data.concat({
                    name: "_method",
                    value: "PUT"
                });
            }

            $.ajax({
                url: url,
                data: data,
                method: 'Post',
                dataType: 'JSON',
                success: function(data) {
                    if (data.status) {
                        $(".text-error-nama_pembayaran").remove();
                        $(".text-error-kode_pembayaran").remove();
                        $(".text-error-norek_pembayaran").remove();
                        toastr.success(data.msg);
                        $('#form-pembayaran')[0].reset();
                        $('#modal_pembayaran').modal('hide');
                        dataTableNoRek.ajax.reload();

                    } else {
                        $(".text-error-nama_pembayaran").remove();
                        $(".text-error-kode_pembayaran").remove();
                        $(".text-error-norek_pembayaran").remove();
                        $.each(data.data, function(field_name, error) {
                            $(document).find('[name=' + field_name + ']').after(
                                '<small class="text-error-' + field_name +
                                ' text-danger ">' + error + '</small>')
                        });
                        toastr.warning(data.msg);
                    }
                }
            });
        });

        $(document).on('click', '.on-pembayaran', function(e) {
            e.preventDefault();
            let $this = $(this);
            let id = $this.data('id');
            let status = $this.data('status');
            let url = '{{ route('metode_pembayaran.update_status', ['id' => ':id']) }}';
            url = url.replace(":id", id);
            $.ajax({
                url: url,
                data: {
                    'status': status,
                    '_method': "PUT"
                },
                method: 'POST',
                success: function(data) {
                    if (data.status) {
                        Swal.fire(
                            'Berhasil!',
                            data.msg,
                            'success'
                        );
                        dataTableNoRek.ajax.reload();
                    } else {
                        toastr.error(data.msg);
                    }
                }
            });
        });

</script>
@endsection