routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdressController;
use App\Http\Controllers\BannerPromoController;
use App\Http\Controllers\chartController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\FAQController;
// use App\Http\Controllers\FrontendProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MasterCategoryController;
use App\Http\Controllers\MasterProductController;
use App\Http\Controllers\MasterSizeController;
use App\Http\Controllers\MetodePembayaranController;
use App\Http\Controllers\PreviewProdukControlller;
use App\Http\Controllers\StoreSettingController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoucherKodeController;
use App\Http\Controllers\WeightOngkirController;
use App\Http\Controllers\KataSandiController;
use App\Models\MasterCategory;
use Illuminate\Support\Facades\DB;
// use Illuuse App\Http\Controllers\StoreSettingController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::prefix('/chart')->group(function () {
    Route::get('/wilshit', [chartController::class, 'wilshit'])->name('chart.wilshit');
});

// chart to checkout
Route::resource('/chart', chartController::class);

#================================ ROUTE ADMIN TRANSAKSION ===================================================
Route::middleware('auth', 'role:admin')->group(function () {
    Route::post('ubah_password',[KataSandiController::class,'reset'])->name('proses.reset.password');
    Route::resource('/admin', AdminController::class);
    Route::group(['prefix' => 'admin'], function () {
        // Route::resource('/', AdminController::class)->name('admin.index');
        Route::get('/transaksi/rejected', [TransaksiController::class, 'rejected_view'])->name('admin_transaksi.rejected');
        Route::get('/transaksi/selesai', [TransaksiController::class, 'selesai_view'])->name('admin_transaksi.selesai');
        Route::get('/transaksi/all', [TransaksiController::class, 'all_transaksi'])->name('admin_transaksi.all');
        Route::put('/transaksi/update_transaksi', [TransaksiController::class, 'update_transaksi'])->name('admin_transaksi.update_transaksi');
        Route::put('/transaksi/update_tracking', [TransaksiController::class, 'update_tracking'])->name('admin_transaksi.update_tracking');
    });
});
Route::get('admin/transaksi/detail/', [TransaksiController::class, 'detail_transaksi'])->name('admin_transaksi.detail_transaksi');
#================================ ROUTE ADMIN TRANSAKSION ===================================================

// Route::middleware('auth', 'role:admin')->group(function () {
//     Route::resource('/admin', AdminController::class);
// });


Route::get('/', [HomeController::class, 'index'])->name('homepage');


Route::prefix('customer')->group(function () {
    Route::prefix('account')->group(function () {
        Route::get('login', [LoginController::class, 'index'])->name('login')->middleware('guest');
        Route::post('login', [LoginController::class, 'login'])->name('login.post');
        Route::post('logout', [LoginController::class, 'logout'])->name('logout');
        Route::post('registrasi', [LoginController::class, 'registrasi'])->name('registrasi');
    });
});

// ====================================================== route admin ========================================================================
// master
Route::middleware('auth', 'role:admin')->group(function () {
    Route::group(['prefix' => 'master'], function () {
        // master size
        Route::group(['prefix' => 'size'], function () {
            Route::get('/', [MasterSizeController::class, 'index'])->name('master_size');
            Route::get('/sizes', [MasterSizeController::class, 'show_data'])->name('data_size');
            Route::post('/', [MasterSizeController::class, 'store'])->name('tambah_size');
            Route::get('{id}', [MasterSizeController::class, 'edit'])->name('get_size');
            Route::put('/', [MasterSizeController::class, 'update'])->name('update_size');
            Route::delete('/', [MasterSizeController::class, 'destroy'])->name('hapus_size');
        });

        // master category
        Route::group(['prefix' => 'category'], function () {
            Route::get(
                '/',
                [MasterCategoryController::class, 'index']
            )->name('master_category');
            Route::get('/categorys', [MasterCategoryController::class, 'show_data'])->name('data_category');
            Route::post('/', [MasterCategoryController::class, 'store'])->name('tambah_category');
            Route::get('{id}', [MasterCategoryController::class, 'edit'])->name('get_category');
            Route::put(
                '/',
                [MasterCategoryController::class, 'update']
            )->name('update_category');
            Route::delete('/', [MasterCategoryController::class, 'destroy'])->name('hapus_category');
        });

        // master product
        Route::resource('/product', MasterProductController::class);
        Route::get('/products', [MasterProductController::class, 'show_data'])->name('product.dataproduct');
        Route::delete('/remove_item', [MasterProductController::class, 'remove_item'])->name('product.remove_item');
        Route::delete('/remove_kategori', [MasterProductController::class, 'remove_kategori'])->name('product.remove_kategori');
        Route::get('/products/transaksi/list/{id}', [MasterProductController::class, 'list_transaksi_selesai'])->name('product.list_transaksi_selesai');
        // Route::get('/products/penilain/{id}', [MasterProductController::class, 'penilaian_produk'])->name('product.penilaian_produk');

        // previw produk
        Route::resource('products/preview/penilain', PreviewProdukControlller::class);
        // pengaturan toko
        Route::group(['prefix' => 'pengaturan_toko'], function () {
            Route::get('/', [StoreSettingController::class, 'index'])->name('pengaturan_toko');
            Route::get('/tes', [StoreSettingController::class, 'create'])->name('a');
            Route::put('/', [StoreSettingController::class, 'update'])->name('ubah_data_toko');
            Route::put('/update_banner/{id}', [StoreSettingController::class, 'update_banner'])->name('pengaturan_toko.update_banner');
            Route::put('/update_banner_status/{id}', [StoreSettingController::class, 'update_banner_status'])->name('pengaturan_toko.update_status_banner');
            Route::put('/update_background_testimoni', [StoreSettingController::class, 'background_testimoni'])->name('pengaturan_toko.backround_testimoni');
            Route::get('/reviews', [StoreSettingController::class, 'reviews'])->name('pengaturan_toko.reviews');
            Route::get('/review/{id}', [StoreSettingController::class, 'review'])->name('pengaturan_toko.review');
            Route::post('/reviews', [StoreSettingController::class, 'make_review'])->name('pengaturan_toko.post_reviews');
            Route::put('/reviews/{id}', [StoreSettingController::class, 'edit_review'])->name('pengaturan_toko.edit_reviews');
        });

        // user master
        Route::prefix('/user')->group(function () {
            Route::get('/', [UserController::class, 'index'])->name('master.user_index');
        });
        // user contact_us
        Route::prefix('/contact_us')->group(function () {
            Route::get('/', [ContactUsController::class, 'index'])->name('contact_us.index');
        });

        //metode pembayaran
        Route::resource('/metode_pembayaran', MetodePembayaranController::class);
        Route::put('metode_pembayaran/update_status/{id}', [MetodePembayaranController::class, 'update_status'])->name('metode_pembayaran.update_status');

        //weight ongkir
        Route::resource('berat/ongkir', WeightOngkirController::class);

        //update banner promo
        Route::resource('evoucher/banner_promo', BannerPromoController::class);
        //kode voucher
        Route::resource('vocher/promo', VoucherKodeController::class);
        Route::put('vocher/promo/update_status/{id}', [VoucherKodeController::class, 'update_status'])->name('promo.update_status');

        //faq
        Route::get('faq/data', [FAQController::class, 'show_data'])->name('faq.data');
        Route::resource('faq', FAQController::class);
    });
});
// ====================================================== route frontend ========================================================================

// User Menu
Route::middleware('auth', 'role:customer')->group(function () {
    Route::prefix('user')->group(function () {
        // user profile
        Route::get('/profile', [HomeController::class, 'home_user'])->name('user.profile');
        Route::put('/profile', [HomeController::class, 'update_profile'])->name('update.profile');
        Route::put('/change/password', [LoginController::class, 'change_password'])->name('change.password');
        // penutup user profile
        Route::get('/address', [HomeController::class, 'home_address'])->name('user.address');
        Route::put('/change/default_address', [HomeController::class, 'change_default_address'])->name('change.default_address');
    });
});

Route::prefix('data')->group(function () {
    Route::get('kota/{id_address}', [HomeController::class, 'kota'])->name('get.kota');

resources/views/layout_admin/master_product/all_penilaian.blade.php
@extends('template_admin.admin')

@section('title', 'Master Product')
@section('container')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ $title }}</h1>

    </div>

    <!-- Row -->
    <div class="row">
        <!-- Datatables -->
        <div class="col-lg-12">
            {{-- <div class="from-group mb-2">
                <a href="javascript:void(0)" class="btn btn-primary" value="new" onclick="tambah_review()" href="{{ route('product.create') }}"><i class="fa fa-plus-circle"></i> Tambah Review</a>
            </div> --}}
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    {{-- <h6 class="m-0 font-weight-bold text-primary">Produk : {{ $data->nama_produk }} - Stok :
                        {{ $data->stok_sum_qty }}</h6> --}}
                </div>
                <div class="table-responsive p-3">
                    <table class="table align-items-center table-flush" id="dataTable">
                        <thead class="thead-light">
                            <tr>
                                <th>No</th>
                                <th>ID Pemesanan</th>
                                <th>Nama</th>
                                <th>Review</th>
                                <th style="width: 20%">Rating</th>
                                <th>Tanggal</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        {{-- <tfoot>
                            <tr>
                                <th colspan='3'></th>
                                <th colspan='1'>Rata-Rata Rating</th>
                                <th>Total</th>
                                <th colspan='2'></th>
                                <th></th>
                            </tr>
                        </tfoot> --}}
                    </table>
                </div>
            </div>
        </div>
    </div>
    {{-- <div class="modal fade" id="modal_review" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <form enctype="multipart/form-data" id="review-form">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Tambah Review</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div class="form-group">
                        <label for="">Status Review</label>
                        @csrf
                        @method('POST')
                        <div data-toggle="buttons">
                            <input type="hidden" name="id" id="id" value="{{request()->penilain}}">
                            <label class="btn btn-outline-danger " id="btn-post">
                                <input type="radio" name="status" id="post" value="aktif" autocomplete="off"
                                    style="display: none">
                                <i class="fa fa-power-off"></i> Aktif
                            </label>
                            <label class="btn btn-outline-success" id="btn-post1">
                                <input type="radio" name="status" id="post1" value="nonaktif" autocomplete="off"
                                    style="display: none">
                                <i class="fa fa-check"></i> Non Aktif
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="nama">Nama</label>
                        <input type="text" class="form-control" id="nama" name="nama" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label><strong>Foto </strong></label>
                        <div class="custom-file">
                            <input type="file" name="image[]" class="  form-control" id="customFile" autocomplete="off" multiple>

                        </div>
                    </div>
                    <div class="form-group">
                        <label><strong>Rating </strong></label>
                        <div data-toggle="buttons">
                            <label class="btn btn-outline-warning  mx-1" id="btn-rate1">
                                <input type="radio" name="rating" id="rate1" value="1" autocomplete="off"
                                    style="display: none">
                                <i class="fa fa-star"></i> 1
                            </label>
                            <label class="btn btn-outline-warning  mx-1" id="btn-rate2">
                                <input type="radio" name="rating" id="rate2" value="2" autocomplete="off"
                                    style="display: none">
                                <i class="fa fa-star"></i> 2
                            </label>
                            <label class="btn btn-outline-warning  mx-1" id="btn-rate3">
                                <input type="radio" name="rating" id="rate3" value="3" autocomplete="off"
                                    style="display: none">
                                <i class="fa fa-star"></i> 3
                            </label>
                            <label class="btn btn-outline-warning  mx-1" id="btn-rate4">
                                <input type="radio" name="rating" id="rate4" value="4" autocomplete="off"
                                    style="display: none">
                                <i class="fa fa-star"></i> 4
                            </label>
                            <label class="btn btn-outline-warning  mx-1" id="btn-rate5">
                                <input type="radio" name="rating" id="rate5" value="5" autocomplete="off"
                                    style="display: none">
                                <i class="fa fa-star"></i> 5
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="review">Review</label>
                        <textarea class="form-control" name="review" id="review" autocomplete="off"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary btn-save-rev">Save</button>
                </div>
        </form>
    </div>
</div> --}}
{{-- let rev = {!! json_encode($review) !!}; --}}
    <script>
        //
        let id = "%";
        // datatabel
        var table = $('#dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('penilain.index') }}",
                data: function(d) {
                    d.id = id;
                }
            },

            // initComplete: function() {
            //     dtFilter(this.api())
            // },
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'id_pemesanan',
                    name: 'id_pemesanan',
                },
                {
                    data: 'nama',
                    name: 'nama'
                },
                {
                    data: 'review',
                    name: 'review'
                },
                {
                    data: 'star',
                    name: 'star'
                },
                {
                    data: 'tanggal',
                    name: 'tanggal'
                },
                {
                    data: 'status',
                    name: 'status'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: true,
                    searchable: true
                },
            ]
        });






       /* function tambah_review() {
            $('.btn').removeClass('active');
            $('.btn-save-rev').html('save');
                    $('.btn-save-rev').prop('disabled', false);
            $('#modal_review').modal('show')
        }
        $('#review-form').submit(function(e) {
            e.preventDefault();
            $('.btn-save-rev').html(
                    '<span><i class="fa  fa-spinner fa-spin"></i> &nbsp; Proses</span>');
                    $('.btn-save-rev').prop('disabled', true);
            console.log(e);
            let formData = new FormData(this);
            // console.log(formData)
            var link = "{{ route('penilain.store') }}";
            $.ajax({
                type: 'POST',
                url: link,
                data: formData,
                contentType: false,
                processData: false,
                success: (response) => {
                    console.log(response)
                    if (response.status == true) {
                        this.reset();
                        Swal.fire(
                            'Berhasil!',
                            'backround berhasil diperbaharui!',
                            'success');
                        // table.ajax.reload(dtFilter(table), false);
                        table.ajax.reload();
                        $('#bintang-footer').html(response.bintang);
                        $('#aktif-rev').html(response.all_item);
                        $('#modal_review').modal('hide')
                    } else {
                        $('.btn-save-rev').html('save');
                        $('.btn-save-rev').prop('disabled', false);
                        Swal.fire(
                            'Gagal!',
                            response.msg,
                            'error')
                        $('#image_preview').html('')
                    }
                },
            });
        });*/

        function edit(id, status) {

            let url = "{{ route('penilain.update', ['penilain' => ':id']) }}"
            url = url.replace(':id', id);
            $.ajax({
                method: 'POST',
                url: url,
                data: {
                    status: status,
                    _method: 'PUT'
                },
                success: function(data) {
                    if (data.status) {
                        // console.log(data.bintang);
                        // console.log(data.all_item);
                        Swal.fire(
                            'Berhasil!',
                            'Ubah Status',
                            'success'
                        )
                        // table.ajax.reload(dtFilter(table), false);
                        table.ajax.reload();
                        $('#bintang-footer').html(data.bintang);
                        $('#aktif-rev').html(data.all_item);
                    }
                }
            })
        }
    </script>
@endsection

resources/views/layout_admin/master_product/master_product.blade.php
@extends('template_admin.admin')

@section('title', 'Master Product')
@section('container')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Master Product</h1>

    </div>

    <!-- Row -->
    <div class="row">
        <!-- Datatables -->
        <div class="col-lg-12">
            <div class="from-group mb-2">
                <a class="btn btn-primary" value="new" href="{{ route('product.create') }}"><i
                        class="fa fa-plus-circle"></i> Tambah Product</a>
            </div>
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables</h6> -->
                </div>
                <div class="table-responsive p-3">
                    <table class="table align-items-center table-flush" id="dataTable">
                        <thead class="thead-light">
                            <tr>
                                <th>No</th>
                                <th style="width: 30%">Nama Produk</th>
                                {{-- <th>Kategori</th>
                                    <th>Diskon</th> --}}
                                <th>Harga</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script>
        // datatabel
        var table = $('#dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('product.dataproduct') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'gambar',
                    name: 'gambar',
                },
                // {
                //     data: 'id_kategori',
                //     name: 'id_kategori'
                // },
                {
                    data: 'harga_jual',
                    name: 'harga_jual'
                },
                // {
                //     data: 'diskon',
                //     name: 'diskon'
                // },
                {
                    data: 'status_produk',
                    name: 'status_produk'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: true,
                    searchable: true
                },
            ]
        });


        function open_modal(judul, tombolSimpan, method) {
            $('#modal').modal('show');
            $('#tombolsimpan').text(tombolSimpan);
            $('.modal-title').text(judul);
            $('#form')[0].reset();
            if (method != 'edit') {
                $("input[name=id]").val('');
                $("input[name=_method]").val('');
                $('#tombolsimpan').attr('onclick', 'aksi("tambah")')
            } else {
                $('#tombolsimpan').attr('onclick', 'aksi("edit")')
            }
        };

        function tambah() {
            open_modal('Tambah Product', 'Simpan', 'tambah')
        }

        function edit(id) {
            var link = " {{ route('product.edit', 'id') }}";
            var link_tujuan = link.replace("id", id);
            $.ajax({
                type: "get",
                url: link_tujuan,
                success: function(response) {
                    open_modal('Edit Product', 'Ubah', 'edit')
                    $('#id').val(response.id);
                    $('#Product_name').val(response.Product_name);
                    $('#method').html('@method("put")')
                }
            });
        }

        function hapus(id) {
            var link = "{{ route('product.destroy', 'id') }}";
            link = link.replace('id', id)
            Swal.fire({
                title: 'Apakah anda yakin?',
                text: "Data yang dihapus tidak dapat dikembalikan lagi!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal',
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "post",
                        url: link,
                        data: {
                            "id": id,
                            "_method": "delete",
                            "_token": "{{ @csrf_token() }}"
                        },
                        success: function(response) {
                            if (response.success == true) {
                                $('#modal').modal('hide');
                                Swal.fire(
                                    'Berhasil!',
                                    'Data berhasil dihapus!',
                                    'success'
                                )
                                table.ajax.reload();
                            } else {
                                Swal.fire(
                                    'Gagal!',
                                    'Data gagal dihapus!',
                                    'error'
                                )
                            }
                        }
                    });
                }
            })
        }

        function aksi(method) {
            if (method == 'tambah') {
                $.ajax({
                    type: "post",
                    url: "{{ route('product.store') }}",
                    data: $('#form').serialize(),
                    success: function(response) {

                        if (response.success == true) {
                            $('#modal').modal('hide');
                            Swal.fire(
                                'Berhasil!',
                                'Data berhasil disimpan!',
                                'success'
                            )
                            table.ajax.reload();
                        } else {
                            Swal.fire(
                                'Gagal!',
                                'Data gagal disimpan!',
                                'error'
                            )
                        }
                    }
                });

            } else if (method == 'edit') {
                var link = "{{ route('product.update', 'id') }}";
                link = link.replace('id', $('#id').val())
                $.ajax({
                    type: "post",
                    url: link,
                    data: $('#form').serialize(),
                    success: function(response) {
                        if (response.success == true) {
                            $('#modal').modal('hide');
                            Swal.fire(
                                'Berhasil!',
                                'Data berhasil disimpan!',
                                'success'
                            )
                            table.ajax.reload();
                        } else {
                            Swal.fire(
                                'Gagal!',
                                'Data gagal disimpan!',
                                'error'
                            )
                        }
                    }
                });

            }

        }

        // swall if success
        @if (Session::get('data'))
            Swal.fire(
            'Berhasil!',
            '{{ Session::get('data') }}',
            'success'
            )
        @endif
    </script>
@endsection